import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "./components/Navbar"
import dbConnect from './db/dbConnect'
import compareAndUpdateAlbums from '@/app/db/controllers/compareAndUpdateAlbums'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nick K Prather",
  description: "Generated by create next app",
};

const intializeDB = async () => {
  await dbConnect();
  compareAndUpdateAlbums();
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  intializeDB();
  return (
    <html lang="en">
      <body className="flex bg-white dark:bg-gray-900">
        <Navbar />
        <div className="w-full">
          <div className={inter.className}>
            {children}
          </div>
        </div>                
      </body>
    </html>
  );
}
